#!/usr/bin/env python3


import argparse
import json
import os
import sys

from fuzzer.txracer.config import (
    TxRacerConfig,
    add_txracer_arguments,
)
from fuzzer.txracer.evolution.outer import (
    DEFAULT_CANDIDATES_PER_TRIGGER,
    DEFAULT_MAX_ROUNDS,
    DEFAULT_STAGNATION_GENERATIONS,
    OuterEvolutionController,
    SubprocessCrossFuzzRunner,
    load_template_tasks,
)


def _run_single_shot(args, sequence, workdir):

    runner = SubprocessCrossFuzzRunner(
        sol_file=args.sol_file,
        contract_name=args.contract_name,
        solc_version=args.solc_version,
        solc_path=args.solc_path,
        evm_version=args.evm_version,
        generations=args.evolution_generations,
        population=args.evolution_population,
        seed=args.evolution_seed,
        workdir=workdir,
        fuzz_time_per_sequence=args.fuzz_time_per_sequence,
        txracer_flags=_txracer_flags(args),
        sequence_template_path=args.sequence_template,
    )
    metrics = runner.run_sequence(
        sequence, "single_results.json", "asset_feedback_campaign.json")
    record = {
        "schema_version": 1,
        "mode": "single_shot",
        "outer_evolution_enabled": False,
        "sequence": list(sequence),
        "metrics": metrics.to_dict(),
        "note": "outer evolution is OFF by default; the planner's initial "
                "sequence ran once through the campaign (P5-EVO-01/08)",
    }
    with open(os.path.join(workdir, "outer_evolution.json"),
              "w", encoding="utf-8") as handle:
        json.dump(record, handle, indent=2, sort_keys=True)
    print("[*] Single-shot run completed: %s" % metrics.to_dict())
    print("[*] Outer sequence evolution is DISABLED (default). "
          "Use --mode extended --outer-sequence-evolution to enable it.")


def _txracer_flags(args):

    from fuzzer.txracer.config import (
        TxRacerConfig,
        append_txracer_arguments,
    )
    config = TxRacerConfig.from_namespace(args)
    command = []
    append_txracer_arguments(command, config)
    return command


def _positive_int(name):
    from fuzzer.txracer.config import positive_int
    return lambda value: positive_int(value, name=name)


def main():
    parser = argparse.ArgumentParser(
        description="Evolutionary sequencer: stagnation-driven OUTER "
                    "function-sequence evolution (default off).")
    parser.add_argument("sol_file", help="Path to the Solidity source file.")
    parser.add_argument("contract_name", help="Name of the main contract.")
    parser.add_argument("solc_version", help="Solidity compiler version.")
    parser.add_argument("max_seq_len", type=_positive_int("max-seq-len"),
                        help="Maximum length of a transaction sequence "
                             "(positive integer).")
    parser.add_argument("result_path",
                        help="Path to save the temporary results JSON.")
    parser.add_argument("solc_path",
                        help="Absolute path to the solc binary.")
    parser.add_argument("duplication", choices=["0", "1"],
                        help="Duplication mode.")
    parser.add_argument("--constructor_config",
                        help="Constructor config JSON (optional).")
    parser.add_argument("--depend-contracts", nargs="+",
                        help="Dependent contracts in deployment order.")
    parser.add_argument(
        "--debug-sequence",
        help="Run the sequence from the given JSON file once and exit.")
    parser.add_argument(
        "--sequence-template", dest="sequence_template",
        help="Planner template JSON (default: generated by "
             "generate_sequence.py from sol_file).")
    parser.add_argument(
        "--evm-version", dest="evm_version", default="byzantium",
        help="Execution EVM version (default byzantium).")
    parser.add_argument(
        "--fuzz-time-per-sequence", "--evolution-fuzz-time",
        dest="fuzz_time_per_sequence",
        type=_positive_int("fuzz-time-per-sequence"), default=10,
        help="Bounded campaign time per sequence in seconds (default "
             "10; must be a positive integer; drives the inner campaign "
             "with -t). --evolution-fuzz-time is an alias of the same "
             "parameter.")
    parser.add_argument(
        "--evolution-generations", dest="evolution_generations",
        type=_positive_int("evolution-generations"), default=2,
        help="Inner campaign generations per evaluation (default 2).")
    parser.add_argument(
        "--evolution-population", dest="evolution_population",
        type=_positive_int("evolution-population"), default=4,
        help="Inner campaign population size per evaluation (default 4).")
    parser.add_argument(
        "--evolution-seed", dest="evolution_seed", type=int, default=1,
        help="Fixed seed for the inner campaigns (default 1).")

    parser.add_argument(
        "--evolution-stagnation-generations",
        dest="evolution_stagnation_generations",
        type=_positive_int("evolution-stagnation-generations"),
        default=DEFAULT_STAGNATION_GENERATIONS,
        help="Coverage stagnation threshold in rounds (default %d)."
        % DEFAULT_STAGNATION_GENERATIONS)
    parser.add_argument(
        "--evolution-asset-stagnation-generations",
        dest="evolution_asset_stagnation_generations",
        type=_positive_int("evolution-asset-stagnation-generations"),
        default=DEFAULT_STAGNATION_GENERATIONS,
        help="Asset boundary stagnation threshold in rounds (default %d)."
        % DEFAULT_STAGNATION_GENERATIONS)
    parser.add_argument(
        "--evolution-max-rounds", dest="evolution_max_rounds",
        type=_positive_int("evolution-max-rounds"),
        default=DEFAULT_MAX_ROUNDS,
        help="Maximum evolution rounds (default %d)." % DEFAULT_MAX_ROUNDS)
    parser.add_argument(
        "--evolution-candidates", dest="evolution_candidates",
        type=_positive_int("evolution-candidates"),
        default=DEFAULT_CANDIDATES_PER_TRIGGER,
        help="Deterministic candidates per trigger (default %d)."
        % DEFAULT_CANDIDATES_PER_TRIGGER)
    add_txracer_arguments(parser)
    args = parser.parse_args()

    config = TxRacerConfig.from_namespace(args)
    args.txracer_mode = config.mode
    warning = config.inactive_feature_warning()
    if warning:
        print("[!] %s" % warning)

    workdir = os.getcwd()

    if args.debug_sequence:
        with open(args.debug_sequence, "r", encoding="utf-8") as handle:
            sequence = json.load(handle)
        _run_single_shot(args, sequence, workdir)
        return


    template_path = args.sequence_template
    if template_path is None or not os.path.exists(template_path):
        from fuzzer.txracer.planner.sequence_planner import (
            PlannerError,
            plan_sequence_template,
        )
        template_path = "sequence_template.json"
        try:
            template = plan_sequence_template(
                args.sol_file, solc_path=args.solc_path)
        except PlannerError as plan_error:
            print("[!] Planning failed: %s" % plan_error, file=sys.stderr)
            sys.exit(1)
        with open(template_path, "w", encoding="utf-8") as handle:
            json.dump(template, handle, indent=2, sort_keys=True)
    sequence, gene_pool, dependency_map, limitations = load_template_tasks(
        template_path)
    if not sequence:
        print("[!] Empty planned sequence; planning failed or no callable "
              "candidates (see template limitations).", file=sys.stderr)
        sys.exit(1)

    evolution_enabled = bool(config.features.outer_sequence_evolution)
    print("[*] Planned initial sequence (%d tasks): %s"
          % (len(sequence), [task["signature"] for task in sequence]))
    print("[*] Outer sequence evolution enabled: %s"
          % evolution_enabled)
    if limitations:
        print("[*] Planner limitations: %s" % limitations)

    if not evolution_enabled:
        _run_single_shot(args, sequence, workdir)
        return

    runner = SubprocessCrossFuzzRunner(
        sol_file=args.sol_file,
        contract_name=args.contract_name,
        solc_version=args.solc_version,
        solc_path=args.solc_path,
        evm_version=args.evm_version,
        generations=args.evolution_generations,
        population=args.evolution_population,
        seed=args.evolution_seed,
        workdir=workdir,
        fuzz_time_per_sequence=args.fuzz_time_per_sequence,
        txracer_flags=_txracer_flags(args),
        sequence_template_path=None,
    )
    controller = OuterEvolutionController(
        runner=runner,
        gene_pool=gene_pool,
        base_sequence=sequence,
        seed=args.evolution_seed,
        coverage_threshold=args.evolution_stagnation_generations,
        asset_threshold=args.evolution_asset_stagnation_generations,
        candidates_per_trigger=args.evolution_candidates,
        max_rounds=args.evolution_max_rounds,
        dependency_map=dependency_map,
        max_length=args.max_seq_len,
    )
    records = controller.run()
    report = controller.to_dict()
    report["mode"] = "extended"
    report["template"] = template_path
    report["campaign_result_path"] = os.path.basename(args.result_path)
    report["fuzz_time_per_sequence"] = args.fuzz_time_per_sequence
    with open(os.path.join(workdir, "outer_evolution.json"),
              "w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=2, sort_keys=True)
    triggered = sum(
        1 for round_record in records if round_record["triggers"])
    print("[*] Outer evolution completed: %d rounds, %d rounds with "
          "triggers; report written to outer_evolution.json"
          % (len(records), triggered))


if __name__ == "__main__":
    main()
